final List<Map<String, dynamic>> stickers = [
  {
    "titulo": "Frutas e Hortaliças",
    "color": 'green',
    "imagens": [
      {"nome": "Abacate", "image": "assets/images/abacate.png"},
      {"nome": "Abacaxi", "image": "assets/images/abacaxi.png"},
      {"nome": "Abobrinha", "image": "assets/images/abobrinha.png"},
      {"nome": "Alface", "image": "assets/images/alface.png"},
      {"nome": "Banana", "image": "assets/images/banana.png"},
      {"nome": "Batata", "image": "assets/images/batata.png"},
      {"nome": "Batata Doce", "image": "assets/images/batataDoce.png"},
      {"nome": "Berinjela", "image": "assets/images/berinjela.png"},
      {"nome": "Beterraba", "image": "assets/images/beterraba.png"},
      {"nome": "Cenoura", "image": "assets/images/cenoura.png"},
      {"nome": "Chuchu", "image": "assets/images/chuchu.png"},
      {"nome": "Couve", "image": "assets/images/couve.png"},
      {"nome": "Goiaba", "image": "assets/images/goiaba.png"},
      {"nome": "Laranja", "image": "assets/images/laranja.png"},
      {"nome": "Maçã", "image": "assets/images/maça.png"},
      {"nome": "Melancia", "image": "assets/images/melancia.png"},
      {"nome": "Melão", "image": "assets/images/melao.png"},
      {"nome": "Pepino", "image": "assets/images/pepino.png"},
      {"nome": "Tangerina", "image": "assets/images/tangerina.png"},
      {"nome": "Tomate", "image": "assets/images/tomate.png"},
    ],
  },
  {
    "titulo": "Comidas",
    "color": 'blue',
    "imagens": [
      {"nome": "Arroz", "image": "assets/images/arroz.png"},
      {"nome": "Bolo", "image": "assets/images/bolo.png"},
      {"nome": "Carne", "image": "assets/images/carne.png"},
      {"nome": "Feijão", "image": "assets/images/feijao.png"},
      {"nome": "Leite", "image": "assets/images/leite.png"},
      {"nome": "Pão Francês", "image": "assets/images/pao.png"},
      {"nome": "Macarronada", "image": "assets/images/macarrao.png"},
    ],
  },
  {
    "titulo": "Ultraprocessados",
    "color": 'red',
    "imagens": [
      {"nome": "Bolacha recheada", "image": "assets/images/bolacha.png"},
      {"nome": "Miojo", "image": "assets/images/miojo.png"},
      {"nome": "Salgadinho", "image": "assets/images/salgadinho.png"},
    ],
  }
];
